version: '3.4'

services: 
    mysql-workbench-service:
        image: 'naveen/mysql-workbench'
        build: ./
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./mysql-workbench-workspace:/root/.mysql/workbench
        environment:
            - DISPLAY=unix$DISPLAY
        links:
            - "db-server"
        depends_on:
            - "db-server"
    db-server:
        image: wm-b2b-mysql-5.7:test
        container_name: 'b2b-db'
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - MYSQL_DATABASE=test-db
        hostname: 'db-host'
        ports:
            - 3306:3306
            
            
#volumes:
 #   mysql-workbench-workspace:
   #     name: ./mysql-workbench-workspace
